Update wp8_parser.js
Fails to add windows package, files with 0 sizes are not directories.
        [phonegap] adding the Windows Phone 8 platform...
        Fatal error:
        npm\node_modules\phonegap\node_modules\cordova\src\metadata\wp8_parser.
        js:220
                    if(stat.size == 0 {
                                      ^
        SyntaxError: Unexpected token {
            at Module._compile (module.js:439:25)
            at Object.Module._extensions..js (module.js:474:10)
            at Module.load (module.js:356:32)
            at Function.Module._load (module.js:312:12)
            at Module.require (module.js:364:17)
            at Object.defineProperty.get [as parser] (c:\Users\AppData\Roaming\npm\node_modules\phonegap
        \node_modules\cordova\src\util.js:140:55)
            at Function.module.exports.supports (c:\Users\AppData\Roaming\npm\node_modules\phonegap\node
        _modules\cordova\src\platform.js:259:41)
            at call_into_create (c:\Users\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova
        \src\platform.js:295:24)
            at c:\Users\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova\src\platform.js:9
        6:29
            at c:\Users\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova\src\lazy_load.js:
        48:31